# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-11 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='unidad_dosis',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='cantidad_frasco',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='descripcion',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='dosis',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='formato_medicamento',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='homeopatia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nombre_comercial',
            field=models.CharField(default='-', max_length=150),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nombre_generico',
            field=models.CharField(default='-', max_length=150),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='tipo_medicamento',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='ubicacion_actual',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
