# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-12 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20171212_1518'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estaciones',
            new_name='Estacion',
        ),
    ]
