# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-13 03:46
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0006_auto_20171212_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=datetime.datetime.now)),
                ('salida', models.BooleanField()),
                ('descripcion_tipo', models.CharField(blank=True, max_length=150, null=True)),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='dashboard.Estacion')),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='dashboard.Estacion')),
            ],
        ),
        migrations.CreateModel(
            name='Orden_Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Medicamento')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Orden')),
            ],
        ),
        migrations.RenameModel(
            old_name='Tipo_Ingreso',
            new_name='Tipo_Orden',
        ),
        migrations.RemoveField(
            model_name='orden_ingreso',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='orden_ingreso',
            name='medicamento',
        ),
        migrations.RemoveField(
            model_name='orden_ingreso',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='orden_salida',
            name='medicamento',
        ),
        migrations.RemoveField(
            model_name='orden_salida',
            name='origen',
        ),
        migrations.RemoveField(
            model_name='orden_salida',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='Orden_Ingreso',
        ),
        migrations.DeleteModel(
            name='Orden_Salida',
        ),
        migrations.DeleteModel(
            name='Tipo_Egreso',
        ),
        migrations.AddField(
            model_name='orden',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Tipo_Orden'),
        ),
        migrations.AddField(
            model_name='orden',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
