# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-19 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20171213_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='unidad_dosis',
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='dosis',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
