# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-24 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20171219_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='dashboard.Estacion'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='dashboard.Estacion'),
        ),
    ]
