# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-24 15:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20180224_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha_hora',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 24, 15, 42, 27, 275187, tzinfo=utc)),
        ),
    ]
