# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-24 15:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20180224_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha_hora',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
