# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-26 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20180224_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_orden',
            name='clase',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
