# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-09 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeopatia', models.BooleanField()),
                ('nombre_comercial', models.CharField(max_length=150)),
                ('nombre_generico', models.CharField(max_length=150)),
                ('cantidad_frasco', models.CharField(max_length=50)),
                ('dosis', models.CharField(max_length=50)),
                ('stock_farmacia', models.IntegerField(default=0)),
                ('stock_bodega', models.IntegerField(default=0)),
                ('formato_medicamento', models.CharField(max_length=50)),
                ('tipo_medicamento', models.CharField(max_length=100)),
                ('ubicacion_actual', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
