# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-12 15:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20171211_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Orden_Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=datetime.datetime.now)),
                ('cantidad', models.IntegerField()),
                ('descripcion_tipo', models.CharField(blank=True, default='', max_length=150)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Estaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Orden_Salida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=datetime.datetime.now)),
                ('cantidad', models.IntegerField()),
                ('descripcion_tipo', models.CharField(blank=True, default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Egreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='stock_bodega',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='stock_farmacia',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='ubicacion_actual',
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='cantidad_frasco',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Medicamento'),
        ),
        migrations.AddField(
            model_name='orden_salida',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Medicamento'),
        ),
        migrations.AddField(
            model_name='orden_salida',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Estaciones'),
        ),
        migrations.AddField(
            model_name='orden_salida',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Tipo_Egreso'),
        ),
        migrations.AddField(
            model_name='orden_ingreso',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Medicamento'),
        ),
        migrations.AddField(
            model_name='orden_ingreso',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Tipo_Ingreso'),
        ),
    ]
