# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-12 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20171212_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento_Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Medicamento')),
            ],
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='medicamento',
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='ubicacion',
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name='medicamento_ubicacion',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Ubicacion'),
        ),
    ]
